language: node_js
node_js:
- '6'
branches:
  only:
  - master
before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: hacgoKCyVmiL4r5wVqAzX+2eRJjQu3bZCCCj6hVfgp+8chpJv5m7RXEkYUjINkPuzdKa7VXr+P2wNsrfbSEs185ZxuAl1khUhLAN3MQ1eImdko0TQr6Y7r3JQXgl+lZJP63V/7r+v9mg5PTc2F8ES7orTc0+KsMVgNZ4Y8MiqFgziSCfsfpnZk5sUmweXkrg1jQaT9tKd5e8HHUOoFdnoiXlSy8fi1NBPz/oeqzCezqWb23UCS2mKT0JwL4Kk9QFuzT5OZYwTSQbYmpB0+Tm2K7p6/3+/TOZ1/VZ6rVv2FI6GCcSLErMKqI+9QfFGH+MtWZNN/M7wLSm0bl84ECe0GOq+p0+4/JYQUBViXnaFQpQrLjgSkt/oCCGEp3cmVvgi7w2Yiz2KpNxVQZ7dl7fIbnbY9G076B35pHQJYngB1hGar1vJLutZWTh6Ko2/Docolh/R25rOLqafpruEGHCENB+Pm3qtsbuPj6I4y61MIUlA6hUdb6ZDTdDdWs7jP0f1mQADD+zA7su4FisckbGQ7T4Lg2159euqhE4z3N/AJCh4WBIx7bcxFvEFEipoG5Fv4BZ1jUJ5x5XZqJYmx0X9QjImIK+zahPA6pGNU9OHl3v7A9Drm7wiZmRmY+AOLJk0s1W+SefFlNThEV4CGTfZY3+ariFFdESebNM1BZtuHM=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: MkrA6BfgmUTm6Ts9wjibSmOZ0aWNJrfrRylIm2AXNnd7A2YfnLIHAsNmoDhbdxIn4b9n26HGRpm5YDuYD0+R+LoNZ/X9nqmx4xx1t41z4ACDNll5RdgfX12ilWwqTpObog6XibH6IZzFkSB2cO6VWP9gtqraOhniF/59ag2rjm/WqnfscnYHqJI4jR0MV2aNyt4bm/NHIcJPfBVLuEtktxcbtpEqDAhMTryt5KLVJTVLivfwl8RFpzObYHMJklEkzwvMBURS5vXZOCWnqcEHVy25OB0EmB87ip2iJl9+CZ5k8J6xl0sY/fhAKAj8YAEwPWPs9h1n6fDvgj0Ggyc1JCr8v+SjGVuHfgx60s1wxAWqBq8IgrOMVoN0Vr+DJ0QJ9CPUmftszWtzxCM7FiAXThGoY/XeYR3gC1TVXFpzbtYzxj4VN1kDw3aDG5uIp2VI7nEguFYM7iD5c7OJSt7p5wczk6YLunyWrm9mcbf001Elk1EAO7GA0iuYLjgwPb4aMkkk9jZcB3yMNUdiOW7rgiKXKurIBOrnzQkdAXaRA4C8hugtoswcFd4qDLEQQhZohIBvx/6LDcsHAYs54h68JasfBAqgYkXB/4o++wih3DkHmIKKyjEz1q4BegGaKYkBaqo0kc9+yCjEHom2hpp2nUPDskt3GhgYb0KDQKbECx0=
sudo: false
